### ISSUE TITLE
уточнить у беленькой насколько можно библиотечными функциями пользоваться

### ISSUE THREAD

**Issue by blackmius** [blackmius/bug-free-octo-adventure#3]
https://github.com/blackmius/bug-free-octo-adventure/blob/27a95335f70e2b26b08b20125f2439e2e52fa004/src/Pinger.cpp#L13

штука которая резолвит имена по aliases а потом по днс 
ну вообще грех не пользоваться тем, что уже написано, но все же, другие челы сами реализовывали

**Comment by meowshi** [comment]
Без понятия как это самим реализовать.

**Comment by meowshi** [comment]
сказала можно
